### ISSUE TITLE
[FR] Relax TF version

### ISSUE THREAD

**Issue by sniafas** [ilias-ant/tf-notify#2]
Excellent and very influential.
Can we relax TF version? lets say generally for TF v2

**Comment by ilias-ant** [comment]
@sniafas thank you for the input :)

I have released a [new version (0.2.0)](https://github.com/ilias-ant/tf-notify/releases/tag/0.2.0), where the `TensorFlow` dependency has been relaxed to support versions: `2.7`, `2.8`, `2.9` along with [corresponding CI builds for these versions](https://github.com/ilias-ant/tf-notify/actions/runs/2757091085).

I will think about extending support to earlier versions as well, but the python-version vs tensorflow-version compatibility becomes less straightforward.

Supporting the last 4 python versions & the last 3 tensorflow versions provides a good base for relatively new projects.
